const strings = {
  welcomeText:
    'Manage, search, and secure your contacts effortlessly, syncing across devices for quick communication and simplifying connections.',
  continueWithGoogle: 'Continue with Google',
  welcomeToConnect: 'Welcome To Connect',
  deleteNumberText: `Are you sure you want to delete this contact? This action can't be undone.`,
  call: 'Call',
  message: 'Message',
  email: 'Email',
  share: 'Share',
  contactInfo: 'Contact Info',
  deleteContact: 'Delete contact',
  yesDelete: 'Yes, Delete!',
  noKeep: 'No, Keep it!',
  deleting: 'Deleting...',
  loadingContact: 'Loading contact...',
  contactNotFound: 'Contact not found.',
  unableLoadContact: 'Unable to load contact',
  unableEditContact: 'Unable to edit contact',
  unableDeleteContact: 'Unable to delete contact',
  unableCompleteAction: 'Unable to complete action',
  requireAccess: 'Connect needs to access your contacts.',
  contactsPermissionTitle: 'Connect would like to view your contacts',
  contactsPermissionDenied: 'Contacts access was denied. Please enable it from settings to continue.',
  openSettings: 'Open Settings',
  unableLoadContacts: 'Unable to load contacts',
  unableRequestContactsPermission: 'Unable to request permission',
  unableCreateContact: 'Unable to create contact',
  grantPermission: 'Grant Permission',
  searchContacts: 'Search contacts',
  noResultsFound: 'No results found',
  noContactsYet: 'No contacts yet',
  noFavoritesYet: 'No favorites yet',
  contactsSearchEmptyDescription: 'Try a different name or clear your search to see all contacts.',
  favoritesSearchEmptyDescription: 'Try a different name or clear your search to see your favorites again.',
  contactsEmptyDescription: 'Your saved contacts will show up here once they are available.',
  favoritesEmptyDescription: 'Add your go-to people to favorites so they are easier to reach from here.',
  addFavorite: 'Add favorite',
  addToFavorites: 'Add to favorites',
  removeFromFavorites: 'Remove from favorites',
  removedFromFavorites: 'Removed from favorites',
  undo: 'Undo',
  goBack: 'Go back',
  contacts: 'Contacts',
  favorites: 'Favorites',
  profile: 'Profile',
  errorMessage: 'Something went wrong! Please try again later.',
  save: 'Save',
  saving: 'Saving..',
  editContact: 'Edit Contact',
  createContact: 'Create Contact',
  update: 'Update',
  updating: 'Updating..',
  add: 'Add',
  signOut: 'Sign Out',
  select: 'Select',
  selectAll: 'Select all',
  cancel: 'Cancel',
  okay: 'Okay',
  confirmationMessage: 'Are you sure you want to do this?',
  leave: 'Leave',
  stay: 'Stay',
  signOutMessage: 'We’ll be a little sad to see you go, and your Connect space will miss you until you come back.',
  done: 'Done',
  selectContacts: 'Select Contacts',
} as const;

export default strings;
