const strings = {
  welcomeText:
    'Manage, search, and secure your contacts effortlessly, syncing across devices for quick communication and simplifying connections.',
  continueWithGoogle: 'Continue with Google',
  welcomeToConnect: 'Welcome To Connect',
  deleteNumberText: `Are you sure you want to delete this contact? This action can't be undone.`,
  call: 'Call',
  message: 'Message',
  email: 'Email',
  share: 'Share',
  contactInfo: 'Contact Info',
  deleteContact: 'Delete contact',
  yesDelete: 'Yes, Delete!',
  noKeep: 'No, Keep it!',
  deleting: 'Deleting...',
  loadingContact: 'Loading contact...',
  contactNotFound: 'Contact not found.',
  unableLoadContact: 'Unable to load contact',
  unableEditContact: 'Unable to edit contact',
  unableDeleteContact: 'Unable to delete contact',
  unableCompleteAction: 'Unable to complete action',
  requireAccess: 'Connect needs to access your contacts.',
  contacts: 'Contacts',
  favorites: 'Favorites',
  profile: 'Profile',
  errorMessage: 'Something went wrong! Please try again later.',
  save: 'Save',
  saving: 'Saving..',
  editContact: 'Edit Contact',
  createContact: 'Create Contact',
  update: 'Update',
  updating: 'Updating..',
  add: 'Add',
  signOut: 'Sign Out',
  select: 'Select',
  selectAll: 'Select all',
  cancel: 'Cancel',
  okay: 'Okay',
  confirmationMessage: 'Are you sure you want to do this?',
  leave: 'Leave',
  stay: 'Stay',
  signOutMessage: 'We’ll be a little sad to see you go, and your Connect space will miss you until you come back.',
  done: 'Done',
  selectContacts: 'Select Contacts',
} as const;

export default strings;
